spring:
  datasource:
    url: jdbc:mysql://localhost:13306/url_shortner_db?serverTimezone=UTC
    username: url_shortner_user # 읽기 쓰기 권한만 있는 사용자 지정
    password: url_shortner_user_pw
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100

  flyway:
    enabled: true
    user: url_shortner_admin
    password: url_shortner_pw
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:/db/migration

  jpa:
    properties:
      hibernate:
        legacy_limit_handler: true
        default_batch_fetch_size: 1000
    database: mysql
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

  redis:
    host: localhost
    port: 6999

server:
  port: 8080
